version: '3.8'

services:
  holidayapi:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      - DATABASE_PATH=./data/holidays.db
      - MIGRATIONS_PATH=./migrations
      - RATE_LIMIT_RPM=60
      - RATE_LIMIT_BURST=10
      - ADMIN_API_KEY=admin-secret-key
    volumes:
      - ./data:/root/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
